lastupdatecheck: 0
recentrepos:
- /mnt/c/Users/jkagiwada/Documents/Git-Repos/dotfiles
- /home/josh/Git-Repos/dotfiles
- /mnt/c/Users/jkagiwada/Documents/Git-Repos/Core
- /home/josh/Git-Repos/core
- /mnt/c/Users/jkagiwada/Documents/Git-Repos/scripts
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
